<?php
/**
 * Single Post Template
 *
 * Displays single posts
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

<?php
	$thumb 			= get_post_thumbnail_id($post->ID);
	$img_url 		= wp_get_attachment_url( $thumb,'full');
	$profpic		= get_field('professor_picture');
	$prof_name		= get_the_title();
?>

	<div id="content-header" style="background-image: url(<?php echo($img_url); ?>);">
		<h2><?php echo($prof_name); ?></h2>
	</div>

	<div id="content" class="content-area">
			<main id="main" class="site-main" role="main">

				<?php while ( have_posts() ) : the_post(); ?>

					<div class="headshot">
						<img src="<?php echo($profpic); ?>" alt="Picture of <?php echo($prof_name); ?>" />
					</div>

					<?php echo(the_content()); ?>

				<?php endwhile; // end of the loop. ?>
				
			</main><!-- #main -->

			<?php get_sidebar(); ?>
	</div><!-- #content -->
<?php get_footer(); ?>
