<?php
/**
 * Main Content Template
 *
 * Contains main looop
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
responsive_mobile_entry_before(); ?>

 <div class="course-holder" data-post-type="course">
            <?php

            	$course = new WP_Query( array( 'post_type' => 'course' ) );
                if ($course->have_posts()) {
                    while (have_posts()) : the_post(); ?>

                    <article class="elr-col-lg-3 elr-col-md-3 elr-col-sm-6 product-archive-image-holder">

                        <?php $terms = get_the_terms( get_the_ID(), 'category_courses' );
                            if ( $terms && ! is_wp_error( $terms ) ) : 
                                $subject_links = array();
     
                                foreach ( $terms as $term ) {
                                    $subject_links[] = $term->name;
                                }
                             
                                $course_tag = join( ", ", $subject_links );
                                $course_class = strtolower(str_replace(' ', '_', $course_tag));
                        ?>
                            <span class="subject_tag <?php printf( esc_html( $course_class ) ); ?>">
                                <?php printf( esc_html( $course_tag ) ); ?>
                            </span>
                        <?php endif; ?>

                    	<a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>" class="course-link"></a>
                        <div class="entry-content">
							<?php if ( has_post_thumbnail() ) : ?>
								<?php the_post_thumbnail(); ?>
							<?php endif; ?>
							<div class="course-title">
								<h4><?php the_title(); ?></h4>
								<p class="learn"><i class="fa fa-file-text-o"></i> Learn More</p>
							</div>
						</div>
                    </article>
                    <?php endwhile;
                    wp_reset_postdata();
                } else {
                    return 'No Product Found';
                }
            ?>
   </div>

<?php responsive_mobile_entry_after(); ?>