<?php
/**
 * Template Name: Certification Template
 *
 * Template for Certifications Courses
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

<?php
	
	$course_id		= get_the_ID();
	$thumb 			= get_post_thumbnail_id($post->ID);
	$img_url 		= wp_get_attachment_url( $thumb,'full');
	$enroll 		= get_field('enroll');
	$start 			= get_field('course_start');
	$length 		= get_field('course_length');
	$time 			= get_field('time_requirement');
	$profname 		= get_field('professor_name');
	$profbio		= get_field('professor_bio');
	$profpic		= get_field('professor_pic');
	$proflink		= get_field('professor_link');
	$certificate	= get_field('certificate');
	$tuition		= get_field('tuition');

	if($start != ''){
		$start 		= date("M j, Y", strtotime($start));

		//return $start;
	}
   
?>

	<div id="content-header" style="background-image: url(<?php echo($img_url); ?>);">
		<h2><?php echo(get_the_title()); ?></h2>
		<p><a href="<?php echo($enroll); ?>" class="button enroll standalone red">Enroll Now</a></p>
	</div>
	<div id="course-info">
		<ul>
			<li class="start"><span>Course Start</span><?php echo($start); ?></li>
			<li class="professor"><span>Professor</span><?php echo($profname); ?></li>
			<li class="workload"><span>Workload</span><?php echo($time); ?> Hours</li>
			<li class="certificate"><span>Certificate Offered</span><?php echo($certificate) ?></li>
			<li class="tuition"><span>Tuition</span><?php echo('$' . $tuition); ?></li>
		</ul>
	</div>

	<div id="content-full" class="content-area">
		<main id="main" class="site-main full-width" role="main">
			<div class="row related-courses">
				<div class="related-course"><a href="#">Course Name</a></div>
				<div class="related-course"><a href="#">Course Name</a></div>
				<div class="related-course"><a href="#">Course Name</a></div>
				<div class="related-course"><a href="#">Course Name</a></div>
				<div class="related-course"><a href="#">Course Name</a></div>
			</div>

			<?php while ( have_posts() ) : the_post(); ?>

				<?php echo(the_content()); ?>

			<?php endwhile; // end of the loop. ?>
			
			<div id="professor">
				<div class="headshot">
					<img src="<?php echo($profpic); ?>" alt="Picture of <?php echo($profname); ?>" />
				</div>
				<div class="professorinfo">
					<h4><?php echo($profname); ?></h4>
					<p><?php echo($profbio); ?></p>
				</div>
				<div class="clearfix">&nbsp;</div>
			</div>
			<div class="enroll-container"><a href="<?php echo($enroll); ?>" class="button enroll standalone red">Enroll Now</a></div>

		</main><!-- #main -->
	</div><!-- #content -->
<?php get_footer(); ?>
